enum Color {RED, BLUE, WHITE};
enum Gender {MALE, FEMALE};
enum Month {JAN, FEB = 4, MAR};
enum Skill {C = 3, CPP = 5, JAVA = 2};
console.log(Color.BLUE);
console.log(Gender.MALE);
console.log(Month.JAN);
console.log(Month.FEB);
console.log(Month.MAR);
console.log(Skill.C);
console.log(Skill.CPP);
console.log(Skill.JAVA);
